service:
  name: app

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-domain-manager
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: dev

package:
  individually: true

custom:
  customDomain:
      domainName: resuelveapi.eddusoft.com
      basePath: ''
      stage: ${self:provider.stage}
      createRoute53Record: true
  serverless-offline:
    port: 3000
  optimize:
    external: ['swagger-ui-dist']

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
